// Code generated by counterfeiter. DO NOT EDIT.
package clientfakes

import (
	"sync"

	"github.com/edenreich/n8n-cli/n8n"
)

type FakeClientInterface struct {
	CreateCredentialStub        func(*n8n.Credential) (*n8n.CreateCredentialResponse, error)
	createCredentialMutex       sync.RWMutex
	createCredentialArgsForCall []struct {
		arg1 *n8n.Credential
	}
	createCredentialReturns struct {
		result1 *n8n.CreateCredentialResponse
		result2 error
	}
	createCredentialReturnsOnCall map[int]struct {
		result1 *n8n.CreateCredentialResponse
		result2 error
	}
	CreateProjectStub        func(string) error
	createProjectMutex       sync.RWMutex
	createProjectArgsForCall []struct {
		arg1 string
	}
	createProjectReturns struct {
		result1 error
	}
	createProjectReturnsOnCall map[int]struct {
		result1 error
	}
	CreateVariableStub        func(*n8n.Variable) error
	createVariableMutex       sync.RWMutex
	createVariableArgsForCall []struct {
		arg1 *n8n.Variable
	}
	createVariableReturns struct {
		result1 error
	}
	createVariableReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteCredentialStub        func(string) error
	deleteCredentialMutex       sync.RWMutex
	deleteCredentialArgsForCall []struct {
		arg1 string
	}
	deleteCredentialReturns struct {
		result1 error
	}
	deleteCredentialReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteExecutionStub        func(string) error
	deleteExecutionMutex       sync.RWMutex
	deleteExecutionArgsForCall []struct {
		arg1 string
	}
	deleteExecutionReturns struct {
		result1 error
	}
	deleteExecutionReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteVariableStub        func(string) error
	deleteVariableMutex       sync.RWMutex
	deleteVariableArgsForCall []struct {
		arg1 string
	}
	deleteVariableReturns struct {
		result1 error
	}
	deleteVariableReturnsOnCall map[int]struct {
		result1 error
	}
	GetCredentialSchemaStub        func(string) (map[string]interface{}, error)
	getCredentialSchemaMutex       sync.RWMutex
	getCredentialSchemaArgsForCall []struct {
		arg1 string
	}
	getCredentialSchemaReturns struct {
		result1 map[string]interface{}
		result2 error
	}
	getCredentialSchemaReturnsOnCall map[int]struct {
		result1 map[string]interface{}
		result2 error
	}
	GetProjectsStub        func(*int, string) (*n8n.ProjectList, error)
	getProjectsMutex       sync.RWMutex
	getProjectsArgsForCall []struct {
		arg1 *int
		arg2 string
	}
	getProjectsReturns struct {
		result1 *n8n.ProjectList
		result2 error
	}
	getProjectsReturnsOnCall map[int]struct {
		result1 *n8n.ProjectList
		result2 error
	}
	GetVariablesStub        func(*int, string) (*n8n.VariableList, error)
	getVariablesMutex       sync.RWMutex
	getVariablesArgsForCall []struct {
		arg1 *int
		arg2 string
	}
	getVariablesReturns struct {
		result1 *n8n.VariableList
		result2 error
	}
	getVariablesReturnsOnCall map[int]struct {
		result1 *n8n.VariableList
		result2 error
	}
	RetryExecutionStub        func(string, bool) (*n8n.Execution, error)
	retryExecutionMutex       sync.RWMutex
	retryExecutionArgsForCall []struct {
		arg1 string
		arg2 bool
	}
	retryExecutionReturns struct {
		result1 *n8n.Execution
		result2 error
	}
	retryExecutionReturnsOnCall map[int]struct {
		result1 *n8n.Execution
		result2 error
	}
	UpdateVariableStub        func(string, *n8n.Variable) error
	updateVariableMutex       sync.RWMutex
	updateVariableArgsForCall []struct {
		arg1 string
		arg2 *n8n.Variable
	}
	updateVariableReturns struct {
		result1 error
	}
	updateVariableReturnsOnCall map[int]struct {
		result1 error
	}
	ActivateWorkflowStub        func(string) (*n8n.Workflow, error)
	activateWorkflowMutex       sync.RWMutex
	activateWorkflowArgsForCall []struct {
		arg1 string
	}
	activateWorkflowReturns struct {
		result1 *n8n.Workflow
		result2 error
	}
	activateWorkflowReturnsOnCall map[int]struct {
		result1 *n8n.Workflow
		result2 error
	}
	CreateTagStub        func(string) (*n8n.Tag, error)
	createTagMutex       sync.RWMutex
	createTagArgsForCall []struct {
		arg1 string
	}
	createTagReturns struct {
		result1 *n8n.Tag
		result2 error
	}
	createTagReturnsOnCall map[int]struct {
		result1 *n8n.Tag
		result2 error
	}
	CreateWorkflowStub        func(*n8n.Workflow) (*n8n.Workflow, error)
	createWorkflowMutex       sync.RWMutex
	createWorkflowArgsForCall []struct {
		arg1 *n8n.Workflow
	}
	createWorkflowReturns struct {
		result1 *n8n.Workflow
		result2 error
	}
	createWorkflowReturnsOnCall map[int]struct {
		result1 *n8n.Workflow
		result2 error
	}
	DeactivateWorkflowStub        func(string) (*n8n.Workflow, error)
	deactivateWorkflowMutex       sync.RWMutex
	deactivateWorkflowArgsForCall []struct {
		arg1 string
	}
	deactivateWorkflowReturns struct {
		result1 *n8n.Workflow
		result2 error
	}
	deactivateWorkflowReturnsOnCall map[int]struct {
		result1 *n8n.Workflow
		result2 error
	}
	DeleteWorkflowStub        func(string) error
	deleteWorkflowMutex       sync.RWMutex
	deleteWorkflowArgsForCall []struct {
		arg1 string
	}
	deleteWorkflowReturns struct {
		result1 error
	}
	deleteWorkflowReturnsOnCall map[int]struct {
		result1 error
	}
	GetExecutionByIdStub        func(string, bool) (*n8n.Execution, error)
	getExecutionByIdMutex       sync.RWMutex
	getExecutionByIdArgsForCall []struct {
		arg1 string
		arg2 bool
	}
	getExecutionByIdReturns struct {
		result1 *n8n.Execution
		result2 error
	}
	getExecutionByIdReturnsOnCall map[int]struct {
		result1 *n8n.Execution
		result2 error
	}
	GetExecutionsStub        func(string, bool, string, int, string) (*n8n.ExecutionList, error)
	getExecutionsMutex       sync.RWMutex
	getExecutionsArgsForCall []struct {
		arg1 string
		arg2 bool
		arg3 string
		arg4 int
		arg5 string
	}
	getExecutionsReturns struct {
		result1 *n8n.ExecutionList
		result2 error
	}
	getExecutionsReturnsOnCall map[int]struct {
		result1 *n8n.ExecutionList
		result2 error
	}
	GetTagsStub        func() (*n8n.TagList, error)
	getTagsMutex       sync.RWMutex
	getTagsArgsForCall []struct {
	}
	getTagsReturns struct {
		result1 *n8n.TagList
		result2 error
	}
	getTagsReturnsOnCall map[int]struct {
		result1 *n8n.TagList
		result2 error
	}
	GetWorkflowStub        func(string) (*n8n.Workflow, error)
	getWorkflowMutex       sync.RWMutex
	getWorkflowArgsForCall []struct {
		arg1 string
	}
	getWorkflowReturns struct {
		result1 *n8n.Workflow
		result2 error
	}
	getWorkflowReturnsOnCall map[int]struct {
		result1 *n8n.Workflow
		result2 error
	}
	GetWorkflowTagsStub        func(string) (n8n.WorkflowTags, error)
	getWorkflowTagsMutex       sync.RWMutex
	getWorkflowTagsArgsForCall []struct {
		arg1 string
	}
	getWorkflowTagsReturns struct {
		result1 n8n.WorkflowTags
		result2 error
	}
	getWorkflowTagsReturnsOnCall map[int]struct {
		result1 n8n.WorkflowTags
		result2 error
	}
	GetWorkflowsStub        func(*int, *n8n.WorkflowFilters) (*n8n.WorkflowList, error)
	getWorkflowsMutex       sync.RWMutex
	getWorkflowsArgsForCall []struct {
		arg1 *int
		arg2 *n8n.WorkflowFilters
	}
	getWorkflowsReturns struct {
		result1 *n8n.WorkflowList
		result2 error
	}
	getWorkflowsReturnsOnCall map[int]struct {
		result1 *n8n.WorkflowList
		result2 error
	}
	UpdateWorkflowStub        func(string, *n8n.Workflow) (*n8n.Workflow, error)
	updateWorkflowMutex       sync.RWMutex
	updateWorkflowArgsForCall []struct {
		arg1 string
		arg2 *n8n.Workflow
	}
	updateWorkflowReturns struct {
		result1 *n8n.Workflow
		result2 error
	}
	updateWorkflowReturnsOnCall map[int]struct {
		result1 *n8n.Workflow
		result2 error
	}
	UpdateWorkflowTagsStub        func(string, n8n.TagIds) (n8n.WorkflowTags, error)
	updateWorkflowTagsMutex       sync.RWMutex
	updateWorkflowTagsArgsForCall []struct {
		arg1 string
		arg2 n8n.TagIds
	}
	updateWorkflowTagsReturns struct {
		result1 n8n.WorkflowTags
		result2 error
	}
	updateWorkflowTagsReturnsOnCall map[int]struct {
		result1 n8n.WorkflowTags
		result2 error
	}
	GenerateAuditStub        func(*n8n.PostAuditJSONBody) (*n8n.Audit, error)
	generateAuditMutex       sync.RWMutex
	generateAuditArgsForCall []struct {
		arg1 *n8n.PostAuditJSONBody
	}
	generateAuditReturns struct {
		result1 *n8n.Audit
		result2 error
	}
	generateAuditReturnsOnCall map[int]struct {
		result1 *n8n.Audit
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClientInterface) ActivateWorkflow(arg1 string) (*n8n.Workflow, error) {
	fake.activateWorkflowMutex.Lock()
	ret, specificReturn := fake.activateWorkflowReturnsOnCall[len(fake.activateWorkflowArgsForCall)]
	fake.activateWorkflowArgsForCall = append(fake.activateWorkflowArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ActivateWorkflowStub
	fakeReturns := fake.activateWorkflowReturns
	fake.recordInvocation("ActivateWorkflow", []interface{}{arg1})
	fake.activateWorkflowMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) ActivateWorkflowCallCount() int {
	fake.activateWorkflowMutex.RLock()
	defer fake.activateWorkflowMutex.RUnlock()
	return len(fake.activateWorkflowArgsForCall)
}

func (fake *FakeClientInterface) ActivateWorkflowCalls(stub func(string) (*n8n.Workflow, error)) {
	fake.activateWorkflowMutex.Lock()
	defer fake.activateWorkflowMutex.Unlock()
	fake.ActivateWorkflowStub = stub
}

func (fake *FakeClientInterface) ActivateWorkflowArgsForCall(i int) string {
	fake.activateWorkflowMutex.RLock()
	defer fake.activateWorkflowMutex.RUnlock()
	argsForCall := fake.activateWorkflowArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) ActivateWorkflowReturns(result1 *n8n.Workflow, result2 error) {
	fake.activateWorkflowMutex.Lock()
	defer fake.activateWorkflowMutex.Unlock()
	fake.ActivateWorkflowStub = nil
	fake.activateWorkflowReturns = struct {
		result1 *n8n.Workflow
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) ActivateWorkflowReturnsOnCall(i int, result1 *n8n.Workflow, result2 error) {
	fake.activateWorkflowMutex.Lock()
	defer fake.activateWorkflowMutex.Unlock()
	fake.ActivateWorkflowStub = nil
	if fake.activateWorkflowReturnsOnCall == nil {
		fake.activateWorkflowReturnsOnCall = make(map[int]struct {
			result1 *n8n.Workflow
			result2 error
		})
	}
	fake.activateWorkflowReturnsOnCall[i] = struct {
		result1 *n8n.Workflow
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) CreateTag(arg1 string) (*n8n.Tag, error) {
	fake.createTagMutex.Lock()
	ret, specificReturn := fake.createTagReturnsOnCall[len(fake.createTagArgsForCall)]
	fake.createTagArgsForCall = append(fake.createTagArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.CreateTagStub
	fakeReturns := fake.createTagReturns
	fake.recordInvocation("CreateTag", []interface{}{arg1})
	fake.createTagMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) CreateTagCallCount() int {
	fake.createTagMutex.RLock()
	defer fake.createTagMutex.RUnlock()
	return len(fake.createTagArgsForCall)
}

func (fake *FakeClientInterface) CreateTagCalls(stub func(string) (*n8n.Tag, error)) {
	fake.createTagMutex.Lock()
	defer fake.createTagMutex.Unlock()
	fake.CreateTagStub = stub
}

func (fake *FakeClientInterface) CreateTagArgsForCall(i int) string {
	fake.createTagMutex.RLock()
	defer fake.createTagMutex.RUnlock()
	argsForCall := fake.createTagArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) CreateTagReturns(result1 *n8n.Tag, result2 error) {
	fake.createTagMutex.Lock()
	defer fake.createTagMutex.Unlock()
	fake.CreateTagStub = nil
	fake.createTagReturns = struct {
		result1 *n8n.Tag
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) CreateTagReturnsOnCall(i int, result1 *n8n.Tag, result2 error) {
	fake.createTagMutex.Lock()
	defer fake.createTagMutex.Unlock()
	fake.CreateTagStub = nil
	if fake.createTagReturnsOnCall == nil {
		fake.createTagReturnsOnCall = make(map[int]struct {
			result1 *n8n.Tag
			result2 error
		})
	}
	fake.createTagReturnsOnCall[i] = struct {
		result1 *n8n.Tag
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) CreateWorkflow(arg1 *n8n.Workflow) (*n8n.Workflow, error) {
	fake.createWorkflowMutex.Lock()
	ret, specificReturn := fake.createWorkflowReturnsOnCall[len(fake.createWorkflowArgsForCall)]
	fake.createWorkflowArgsForCall = append(fake.createWorkflowArgsForCall, struct {
		arg1 *n8n.Workflow
	}{arg1})
	stub := fake.CreateWorkflowStub
	fakeReturns := fake.createWorkflowReturns
	fake.recordInvocation("CreateWorkflow", []interface{}{arg1})
	fake.createWorkflowMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) CreateWorkflowCallCount() int {
	fake.createWorkflowMutex.RLock()
	defer fake.createWorkflowMutex.RUnlock()
	return len(fake.createWorkflowArgsForCall)
}

func (fake *FakeClientInterface) CreateWorkflowCalls(stub func(*n8n.Workflow) (*n8n.Workflow, error)) {
	fake.createWorkflowMutex.Lock()
	defer fake.createWorkflowMutex.Unlock()
	fake.CreateWorkflowStub = stub
}

func (fake *FakeClientInterface) CreateWorkflowArgsForCall(i int) *n8n.Workflow {
	fake.createWorkflowMutex.RLock()
	defer fake.createWorkflowMutex.RUnlock()
	argsForCall := fake.createWorkflowArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) CreateWorkflowReturns(result1 *n8n.Workflow, result2 error) {
	fake.createWorkflowMutex.Lock()
	defer fake.createWorkflowMutex.Unlock()
	fake.CreateWorkflowStub = nil
	fake.createWorkflowReturns = struct {
		result1 *n8n.Workflow
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) CreateWorkflowReturnsOnCall(i int, result1 *n8n.Workflow, result2 error) {
	fake.createWorkflowMutex.Lock()
	defer fake.createWorkflowMutex.Unlock()
	fake.CreateWorkflowStub = nil
	if fake.createWorkflowReturnsOnCall == nil {
		fake.createWorkflowReturnsOnCall = make(map[int]struct {
			result1 *n8n.Workflow
			result2 error
		})
	}
	fake.createWorkflowReturnsOnCall[i] = struct {
		result1 *n8n.Workflow
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) DeactivateWorkflow(arg1 string) (*n8n.Workflow, error) {
	fake.deactivateWorkflowMutex.Lock()
	ret, specificReturn := fake.deactivateWorkflowReturnsOnCall[len(fake.deactivateWorkflowArgsForCall)]
	fake.deactivateWorkflowArgsForCall = append(fake.deactivateWorkflowArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DeactivateWorkflowStub
	fakeReturns := fake.deactivateWorkflowReturns
	fake.recordInvocation("DeactivateWorkflow", []interface{}{arg1})
	fake.deactivateWorkflowMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) DeactivateWorkflowCallCount() int {
	fake.deactivateWorkflowMutex.RLock()
	defer fake.deactivateWorkflowMutex.RUnlock()
	return len(fake.deactivateWorkflowArgsForCall)
}

func (fake *FakeClientInterface) DeactivateWorkflowCalls(stub func(string) (*n8n.Workflow, error)) {
	fake.deactivateWorkflowMutex.Lock()
	defer fake.deactivateWorkflowMutex.Unlock()
	fake.DeactivateWorkflowStub = stub
}

func (fake *FakeClientInterface) DeactivateWorkflowArgsForCall(i int) string {
	fake.deactivateWorkflowMutex.RLock()
	defer fake.deactivateWorkflowMutex.RUnlock()
	argsForCall := fake.deactivateWorkflowArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) DeactivateWorkflowReturns(result1 *n8n.Workflow, result2 error) {
	fake.deactivateWorkflowMutex.Lock()
	defer fake.deactivateWorkflowMutex.Unlock()
	fake.DeactivateWorkflowStub = nil
	fake.deactivateWorkflowReturns = struct {
		result1 *n8n.Workflow
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) DeactivateWorkflowReturnsOnCall(i int, result1 *n8n.Workflow, result2 error) {
	fake.deactivateWorkflowMutex.Lock()
	defer fake.deactivateWorkflowMutex.Unlock()
	fake.DeactivateWorkflowStub = nil
	if fake.deactivateWorkflowReturnsOnCall == nil {
		fake.deactivateWorkflowReturnsOnCall = make(map[int]struct {
			result1 *n8n.Workflow
			result2 error
		})
	}
	fake.deactivateWorkflowReturnsOnCall[i] = struct {
		result1 *n8n.Workflow
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) DeleteWorkflow(arg1 string) error {
	fake.deleteWorkflowMutex.Lock()
	ret, specificReturn := fake.deleteWorkflowReturnsOnCall[len(fake.deleteWorkflowArgsForCall)]
	fake.deleteWorkflowArgsForCall = append(fake.deleteWorkflowArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DeleteWorkflowStub
	fakeReturns := fake.deleteWorkflowReturns
	fake.recordInvocation("DeleteWorkflow", []interface{}{arg1})
	fake.deleteWorkflowMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClientInterface) DeleteWorkflowCallCount() int {
	fake.deleteWorkflowMutex.RLock()
	defer fake.deleteWorkflowMutex.RUnlock()
	return len(fake.deleteWorkflowArgsForCall)
}

func (fake *FakeClientInterface) DeleteWorkflowCalls(stub func(string) error) {
	fake.deleteWorkflowMutex.Lock()
	defer fake.deleteWorkflowMutex.Unlock()
	fake.DeleteWorkflowStub = stub
}

func (fake *FakeClientInterface) DeleteWorkflowArgsForCall(i int) string {
	fake.deleteWorkflowMutex.RLock()
	defer fake.deleteWorkflowMutex.RUnlock()
	argsForCall := fake.deleteWorkflowArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) DeleteWorkflowReturns(result1 error) {
	fake.deleteWorkflowMutex.Lock()
	defer fake.deleteWorkflowMutex.Unlock()
	fake.DeleteWorkflowStub = nil
	fake.deleteWorkflowReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientInterface) DeleteWorkflowReturnsOnCall(i int, result1 error) {
	fake.deleteWorkflowMutex.Lock()
	defer fake.deleteWorkflowMutex.Unlock()
	fake.DeleteWorkflowStub = nil
	if fake.deleteWorkflowReturnsOnCall == nil {
		fake.deleteWorkflowReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteWorkflowReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientInterface) GetExecutionById(arg1 string, arg2 bool) (*n8n.Execution, error) {
	fake.getExecutionByIdMutex.Lock()
	ret, specificReturn := fake.getExecutionByIdReturnsOnCall[len(fake.getExecutionByIdArgsForCall)]
	fake.getExecutionByIdArgsForCall = append(fake.getExecutionByIdArgsForCall, struct {
		arg1 string
		arg2 bool
	}{arg1, arg2})
	stub := fake.GetExecutionByIdStub
	fakeReturns := fake.getExecutionByIdReturns
	fake.recordInvocation("GetExecutionById", []interface{}{arg1, arg2})
	fake.getExecutionByIdMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) GetExecutionByIdCallCount() int {
	fake.getExecutionByIdMutex.RLock()
	defer fake.getExecutionByIdMutex.RUnlock()
	return len(fake.getExecutionByIdArgsForCall)
}

func (fake *FakeClientInterface) GetExecutionByIdCalls(stub func(string, bool) (*n8n.Execution, error)) {
	fake.getExecutionByIdMutex.Lock()
	defer fake.getExecutionByIdMutex.Unlock()
	fake.GetExecutionByIdStub = stub
}

func (fake *FakeClientInterface) GetExecutionByIdArgsForCall(i int) (string, bool) {
	fake.getExecutionByIdMutex.RLock()
	defer fake.getExecutionByIdMutex.RUnlock()
	argsForCall := fake.getExecutionByIdArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClientInterface) GetExecutionByIdReturns(result1 *n8n.Execution, result2 error) {
	fake.getExecutionByIdMutex.Lock()
	defer fake.getExecutionByIdMutex.Unlock()
	fake.GetExecutionByIdStub = nil
	fake.getExecutionByIdReturns = struct {
		result1 *n8n.Execution
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GetExecutionByIdReturnsOnCall(i int, result1 *n8n.Execution, result2 error) {
	fake.getExecutionByIdMutex.Lock()
	defer fake.getExecutionByIdMutex.Unlock()
	fake.GetExecutionByIdStub = nil
	if fake.getExecutionByIdReturnsOnCall == nil {
		fake.getExecutionByIdReturnsOnCall = make(map[int]struct {
			result1 *n8n.Execution
			result2 error
		})
	}
	fake.getExecutionByIdReturnsOnCall[i] = struct {
		result1 *n8n.Execution
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GetExecutions(arg1 string, arg2 bool, arg3 string, arg4 int, arg5 string) (*n8n.ExecutionList, error) {
	fake.getExecutionsMutex.Lock()
	ret, specificReturn := fake.getExecutionsReturnsOnCall[len(fake.getExecutionsArgsForCall)]
	fake.getExecutionsArgsForCall = append(fake.getExecutionsArgsForCall, struct {
		arg1 string
		arg2 bool
		arg3 string
		arg4 int
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.GetExecutionsStub
	fakeReturns := fake.getExecutionsReturns
	fake.recordInvocation("GetExecutions", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.getExecutionsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) GetExecutionsCallCount() int {
	fake.getExecutionsMutex.RLock()
	defer fake.getExecutionsMutex.RUnlock()
	return len(fake.getExecutionsArgsForCall)
}

func (fake *FakeClientInterface) GetExecutionsCalls(stub func(string, bool, string, int, string) (*n8n.ExecutionList, error)) {
	fake.getExecutionsMutex.Lock()
	defer fake.getExecutionsMutex.Unlock()
	fake.GetExecutionsStub = stub
}

func (fake *FakeClientInterface) GetExecutionsArgsForCall(i int) (string, bool, string, int, string) {
	fake.getExecutionsMutex.RLock()
	defer fake.getExecutionsMutex.RUnlock()
	argsForCall := fake.getExecutionsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeClientInterface) GetExecutionsReturns(result1 *n8n.ExecutionList, result2 error) {
	fake.getExecutionsMutex.Lock()
	defer fake.getExecutionsMutex.Unlock()
	fake.GetExecutionsStub = nil
	fake.getExecutionsReturns = struct {
		result1 *n8n.ExecutionList
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GetExecutionsReturnsOnCall(i int, result1 *n8n.ExecutionList, result2 error) {
	fake.getExecutionsMutex.Lock()
	defer fake.getExecutionsMutex.Unlock()
	fake.GetExecutionsStub = nil
	if fake.getExecutionsReturnsOnCall == nil {
		fake.getExecutionsReturnsOnCall = make(map[int]struct {
			result1 *n8n.ExecutionList
			result2 error
		})
	}
	fake.getExecutionsReturnsOnCall[i] = struct {
		result1 *n8n.ExecutionList
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GetTags() (*n8n.TagList, error) {
	fake.getTagsMutex.Lock()
	ret, specificReturn := fake.getTagsReturnsOnCall[len(fake.getTagsArgsForCall)]
	fake.getTagsArgsForCall = append(fake.getTagsArgsForCall, struct {
	}{})
	stub := fake.GetTagsStub
	fakeReturns := fake.getTagsReturns
	fake.recordInvocation("GetTags", []interface{}{})
	fake.getTagsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) GetTagsCallCount() int {
	fake.getTagsMutex.RLock()
	defer fake.getTagsMutex.RUnlock()
	return len(fake.getTagsArgsForCall)
}

func (fake *FakeClientInterface) GetTagsCalls(stub func() (*n8n.TagList, error)) {
	fake.getTagsMutex.Lock()
	defer fake.getTagsMutex.Unlock()
	fake.GetTagsStub = stub
}

func (fake *FakeClientInterface) GetTagsReturns(result1 *n8n.TagList, result2 error) {
	fake.getTagsMutex.Lock()
	defer fake.getTagsMutex.Unlock()
	fake.GetTagsStub = nil
	fake.getTagsReturns = struct {
		result1 *n8n.TagList
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GetTagsReturnsOnCall(i int, result1 *n8n.TagList, result2 error) {
	fake.getTagsMutex.Lock()
	defer fake.getTagsMutex.Unlock()
	fake.GetTagsStub = nil
	if fake.getTagsReturnsOnCall == nil {
		fake.getTagsReturnsOnCall = make(map[int]struct {
			result1 *n8n.TagList
			result2 error
		})
	}
	fake.getTagsReturnsOnCall[i] = struct {
		result1 *n8n.TagList
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GetWorkflow(arg1 string) (*n8n.Workflow, error) {
	fake.getWorkflowMutex.Lock()
	ret, specificReturn := fake.getWorkflowReturnsOnCall[len(fake.getWorkflowArgsForCall)]
	fake.getWorkflowArgsForCall = append(fake.getWorkflowArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetWorkflowStub
	fakeReturns := fake.getWorkflowReturns
	fake.recordInvocation("GetWorkflow", []interface{}{arg1})
	fake.getWorkflowMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) GetWorkflowCallCount() int {
	fake.getWorkflowMutex.RLock()
	defer fake.getWorkflowMutex.RUnlock()
	return len(fake.getWorkflowArgsForCall)
}

func (fake *FakeClientInterface) GetWorkflowCalls(stub func(string) (*n8n.Workflow, error)) {
	fake.getWorkflowMutex.Lock()
	defer fake.getWorkflowMutex.Unlock()
	fake.GetWorkflowStub = stub
}

func (fake *FakeClientInterface) GetWorkflowArgsForCall(i int) string {
	fake.getWorkflowMutex.RLock()
	defer fake.getWorkflowMutex.RUnlock()
	argsForCall := fake.getWorkflowArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) GetWorkflowReturns(result1 *n8n.Workflow, result2 error) {
	fake.getWorkflowMutex.Lock()
	defer fake.getWorkflowMutex.Unlock()
	fake.GetWorkflowStub = nil
	fake.getWorkflowReturns = struct {
		result1 *n8n.Workflow
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GetWorkflowReturnsOnCall(i int, result1 *n8n.Workflow, result2 error) {
	fake.getWorkflowMutex.Lock()
	defer fake.getWorkflowMutex.Unlock()
	fake.GetWorkflowStub = nil
	if fake.getWorkflowReturnsOnCall == nil {
		fake.getWorkflowReturnsOnCall = make(map[int]struct {
			result1 *n8n.Workflow
			result2 error
		})
	}
	fake.getWorkflowReturnsOnCall[i] = struct {
		result1 *n8n.Workflow
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GetWorkflowTags(arg1 string) (n8n.WorkflowTags, error) {
	fake.getWorkflowTagsMutex.Lock()
	ret, specificReturn := fake.getWorkflowTagsReturnsOnCall[len(fake.getWorkflowTagsArgsForCall)]
	fake.getWorkflowTagsArgsForCall = append(fake.getWorkflowTagsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetWorkflowTagsStub
	fakeReturns := fake.getWorkflowTagsReturns
	fake.recordInvocation("GetWorkflowTags", []interface{}{arg1})
	fake.getWorkflowTagsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) GetWorkflowTagsCallCount() int {
	fake.getWorkflowTagsMutex.RLock()
	defer fake.getWorkflowTagsMutex.RUnlock()
	return len(fake.getWorkflowTagsArgsForCall)
}

func (fake *FakeClientInterface) GetWorkflowTagsCalls(stub func(string) (n8n.WorkflowTags, error)) {
	fake.getWorkflowTagsMutex.Lock()
	defer fake.getWorkflowTagsMutex.Unlock()
	fake.GetWorkflowTagsStub = stub
}

func (fake *FakeClientInterface) GetWorkflowTagsArgsForCall(i int) string {
	fake.getWorkflowTagsMutex.RLock()
	defer fake.getWorkflowTagsMutex.RUnlock()
	argsForCall := fake.getWorkflowTagsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) GetWorkflowTagsReturns(result1 n8n.WorkflowTags, result2 error) {
	fake.getWorkflowTagsMutex.Lock()
	defer fake.getWorkflowTagsMutex.Unlock()
	fake.GetWorkflowTagsStub = nil
	fake.getWorkflowTagsReturns = struct {
		result1 n8n.WorkflowTags
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GetWorkflowTagsReturnsOnCall(i int, result1 n8n.WorkflowTags, result2 error) {
	fake.getWorkflowTagsMutex.Lock()
	defer fake.getWorkflowTagsMutex.Unlock()
	fake.GetWorkflowTagsStub = nil
	if fake.getWorkflowTagsReturnsOnCall == nil {
		fake.getWorkflowTagsReturnsOnCall = make(map[int]struct {
			result1 n8n.WorkflowTags
			result2 error
		})
	}
	fake.getWorkflowTagsReturnsOnCall[i] = struct {
		result1 n8n.WorkflowTags
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GetWorkflows(arg1 *int, arg2 *n8n.WorkflowFilters) (*n8n.WorkflowList, error) {
	fake.getWorkflowsMutex.Lock()
	ret, specificReturn := fake.getWorkflowsReturnsOnCall[len(fake.getWorkflowsArgsForCall)]
	fake.getWorkflowsArgsForCall = append(fake.getWorkflowsArgsForCall, struct {
		arg1 *int
		arg2 *n8n.WorkflowFilters
	}{arg1, arg2})
	stub := fake.GetWorkflowsStub
	fakeReturns := fake.getWorkflowsReturns
	fake.recordInvocation("GetWorkflows", []interface{}{arg1, arg2})
	fake.getWorkflowsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) GetWorkflowsCallCount() int {
	fake.getWorkflowsMutex.RLock()
	defer fake.getWorkflowsMutex.RUnlock()
	return len(fake.getWorkflowsArgsForCall)
}

func (fake *FakeClientInterface) GetWorkflowsCalls(stub func(*int, *n8n.WorkflowFilters) (*n8n.WorkflowList, error)) {
	fake.getWorkflowsMutex.Lock()
	defer fake.getWorkflowsMutex.Unlock()
	fake.GetWorkflowsStub = stub
}

func (fake *FakeClientInterface) GetWorkflowsArgsForCall(i int) (*int, *n8n.WorkflowFilters) {
	fake.getWorkflowsMutex.RLock()
	defer fake.getWorkflowsMutex.RUnlock()
	argsForCall := fake.getWorkflowsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClientInterface) GetWorkflowsReturns(result1 *n8n.WorkflowList, result2 error) {
	fake.getWorkflowsMutex.Lock()
	defer fake.getWorkflowsMutex.Unlock()
	fake.GetWorkflowsStub = nil
	fake.getWorkflowsReturns = struct {
		result1 *n8n.WorkflowList
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GetWorkflowsReturnsOnCall(i int, result1 *n8n.WorkflowList, result2 error) {
	fake.getWorkflowsMutex.Lock()
	defer fake.getWorkflowsMutex.Unlock()
	fake.GetWorkflowsStub = nil
	if fake.getWorkflowsReturnsOnCall == nil {
		fake.getWorkflowsReturnsOnCall = make(map[int]struct {
			result1 *n8n.WorkflowList
			result2 error
		})
	}
	fake.getWorkflowsReturnsOnCall[i] = struct {
		result1 *n8n.WorkflowList
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) CreateCredential(arg1 *n8n.Credential) (*n8n.CreateCredentialResponse, error) {
	fake.createCredentialMutex.Lock()
	ret, specificReturn := fake.createCredentialReturnsOnCall[len(fake.createCredentialArgsForCall)]
	fake.createCredentialArgsForCall = append(fake.createCredentialArgsForCall, struct {
		arg1 *n8n.Credential
	}{arg1})
	stub := fake.CreateCredentialStub
	fakeReturns := fake.createCredentialReturns
	fake.recordInvocation("CreateCredential", []interface{}{arg1})
	fake.createCredentialMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) CreateCredentialCallCount() int {
	fake.createCredentialMutex.RLock()
	defer fake.createCredentialMutex.RUnlock()
	return len(fake.createCredentialArgsForCall)
}

func (fake *FakeClientInterface) CreateCredentialCalls(stub func(*n8n.Credential) (*n8n.CreateCredentialResponse, error)) {
	fake.createCredentialMutex.Lock()
	defer fake.createCredentialMutex.Unlock()
	fake.CreateCredentialStub = stub
}

func (fake *FakeClientInterface) CreateCredentialArgsForCall(i int) *n8n.Credential {
	fake.createCredentialMutex.RLock()
	defer fake.createCredentialMutex.RUnlock()
	argsForCall := fake.createCredentialArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) CreateCredentialReturns(result1 *n8n.CreateCredentialResponse, result2 error) {
	fake.createCredentialMutex.Lock()
	defer fake.createCredentialMutex.Unlock()
	fake.CreateCredentialStub = nil
	fake.createCredentialReturns = struct {
		result1 *n8n.CreateCredentialResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) CreateCredentialReturnsOnCall(i int, result1 *n8n.CreateCredentialResponse, result2 error) {
	fake.createCredentialMutex.Lock()
	defer fake.createCredentialMutex.Unlock()
	fake.CreateCredentialStub = nil
	if fake.createCredentialReturnsOnCall == nil {
		fake.createCredentialReturnsOnCall = make(map[int]struct {
			result1 *n8n.CreateCredentialResponse
			result2 error
		})
	}
	fake.createCredentialReturnsOnCall[i] = struct {
		result1 *n8n.CreateCredentialResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) CreateProject(arg1 string) error {
	fake.createProjectMutex.Lock()
	ret, specificReturn := fake.createProjectReturnsOnCall[len(fake.createProjectArgsForCall)]
	fake.createProjectArgsForCall = append(fake.createProjectArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.CreateProjectStub
	fakeReturns := fake.createProjectReturns
	fake.recordInvocation("CreateProject", []interface{}{arg1})
	fake.createProjectMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClientInterface) CreateProjectCallCount() int {
	fake.createProjectMutex.RLock()
	defer fake.createProjectMutex.RUnlock()
	return len(fake.createProjectArgsForCall)
}

func (fake *FakeClientInterface) CreateProjectCalls(stub func(string) error) {
	fake.createProjectMutex.Lock()
	defer fake.createProjectMutex.Unlock()
	fake.CreateProjectStub = stub
}

func (fake *FakeClientInterface) CreateProjectArgsForCall(i int) string {
	fake.createProjectMutex.RLock()
	defer fake.createProjectMutex.RUnlock()
	argsForCall := fake.createProjectArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) CreateProjectReturns(result1 error) {
	fake.createProjectMutex.Lock()
	defer fake.createProjectMutex.Unlock()
	fake.CreateProjectStub = nil
	fake.createProjectReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientInterface) CreateProjectReturnsOnCall(i int, result1 error) {
	fake.createProjectMutex.Lock()
	defer fake.createProjectMutex.Unlock()
	fake.CreateProjectStub = nil
	if fake.createProjectReturnsOnCall == nil {
		fake.createProjectReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createProjectReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientInterface) CreateVariable(arg1 *n8n.Variable) error {
	fake.createVariableMutex.Lock()
	ret, specificReturn := fake.createVariableReturnsOnCall[len(fake.createVariableArgsForCall)]
	fake.createVariableArgsForCall = append(fake.createVariableArgsForCall, struct {
		arg1 *n8n.Variable
	}{arg1})
	stub := fake.CreateVariableStub
	fakeReturns := fake.createVariableReturns
	fake.recordInvocation("CreateVariable", []interface{}{arg1})
	fake.createVariableMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClientInterface) CreateVariableCallCount() int {
	fake.createVariableMutex.RLock()
	defer fake.createVariableMutex.RUnlock()
	return len(fake.createVariableArgsForCall)
}

func (fake *FakeClientInterface) CreateVariableCalls(stub func(*n8n.Variable) error) {
	fake.createVariableMutex.Lock()
	defer fake.createVariableMutex.Unlock()
	fake.CreateVariableStub = stub
}

func (fake *FakeClientInterface) CreateVariableArgsForCall(i int) *n8n.Variable {
	fake.createVariableMutex.RLock()
	defer fake.createVariableMutex.RUnlock()
	argsForCall := fake.createVariableArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) CreateVariableReturns(result1 error) {
	fake.createVariableMutex.Lock()
	defer fake.createVariableMutex.Unlock()
	fake.CreateVariableStub = nil
	fake.createVariableReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientInterface) CreateVariableReturnsOnCall(i int, result1 error) {
	fake.createVariableMutex.Lock()
	defer fake.createVariableMutex.Unlock()
	fake.CreateVariableStub = nil
	if fake.createVariableReturnsOnCall == nil {
		fake.createVariableReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createVariableReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientInterface) DeleteCredential(arg1 string) error {
	fake.deleteCredentialMutex.Lock()
	ret, specificReturn := fake.deleteCredentialReturnsOnCall[len(fake.deleteCredentialArgsForCall)]
	fake.deleteCredentialArgsForCall = append(fake.deleteCredentialArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DeleteCredentialStub
	fakeReturns := fake.deleteCredentialReturns
	fake.recordInvocation("DeleteCredential", []interface{}{arg1})
	fake.deleteCredentialMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClientInterface) DeleteCredentialCallCount() int {
	fake.deleteCredentialMutex.RLock()
	defer fake.deleteCredentialMutex.RUnlock()
	return len(fake.deleteCredentialArgsForCall)
}

func (fake *FakeClientInterface) DeleteCredentialCalls(stub func(string) error) {
	fake.deleteCredentialMutex.Lock()
	defer fake.deleteCredentialMutex.Unlock()
	fake.DeleteCredentialStub = stub
}

func (fake *FakeClientInterface) DeleteCredentialArgsForCall(i int) string {
	fake.deleteCredentialMutex.RLock()
	defer fake.deleteCredentialMutex.RUnlock()
	argsForCall := fake.deleteCredentialArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) DeleteCredentialReturns(result1 error) {
	fake.deleteCredentialMutex.Lock()
	defer fake.deleteCredentialMutex.Unlock()
	fake.DeleteCredentialStub = nil
	fake.deleteCredentialReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientInterface) DeleteCredentialReturnsOnCall(i int, result1 error) {
	fake.deleteCredentialMutex.Lock()
	defer fake.deleteCredentialMutex.Unlock()
	fake.DeleteCredentialStub = nil
	if fake.deleteCredentialReturnsOnCall == nil {
		fake.deleteCredentialReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteCredentialReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientInterface) DeleteExecution(arg1 string) error {
	fake.deleteExecutionMutex.Lock()
	ret, specificReturn := fake.deleteExecutionReturnsOnCall[len(fake.deleteExecutionArgsForCall)]
	fake.deleteExecutionArgsForCall = append(fake.deleteExecutionArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DeleteExecutionStub
	fakeReturns := fake.deleteExecutionReturns
	fake.recordInvocation("DeleteExecution", []interface{}{arg1})
	fake.deleteExecutionMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClientInterface) DeleteExecutionCallCount() int {
	fake.deleteExecutionMutex.RLock()
	defer fake.deleteExecutionMutex.RUnlock()
	return len(fake.deleteExecutionArgsForCall)
}

func (fake *FakeClientInterface) DeleteExecutionCalls(stub func(string) error) {
	fake.deleteExecutionMutex.Lock()
	defer fake.deleteExecutionMutex.Unlock()
	fake.DeleteExecutionStub = stub
}

func (fake *FakeClientInterface) DeleteExecutionArgsForCall(i int) string {
	fake.deleteExecutionMutex.RLock()
	defer fake.deleteExecutionMutex.RUnlock()
	argsForCall := fake.deleteExecutionArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) DeleteExecutionReturns(result1 error) {
	fake.deleteExecutionMutex.Lock()
	defer fake.deleteExecutionMutex.Unlock()
	fake.DeleteExecutionStub = nil
	fake.deleteExecutionReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientInterface) DeleteExecutionReturnsOnCall(i int, result1 error) {
	fake.deleteExecutionMutex.Lock()
	defer fake.deleteExecutionMutex.Unlock()
	fake.DeleteExecutionStub = nil
	if fake.deleteExecutionReturnsOnCall == nil {
		fake.deleteExecutionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteExecutionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientInterface) DeleteVariable(arg1 string) error {
	fake.deleteVariableMutex.Lock()
	ret, specificReturn := fake.deleteVariableReturnsOnCall[len(fake.deleteVariableArgsForCall)]
	fake.deleteVariableArgsForCall = append(fake.deleteVariableArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DeleteVariableStub
	fakeReturns := fake.deleteVariableReturns
	fake.recordInvocation("DeleteVariable", []interface{}{arg1})
	fake.deleteVariableMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClientInterface) DeleteVariableCallCount() int {
	fake.deleteVariableMutex.RLock()
	defer fake.deleteVariableMutex.RUnlock()
	return len(fake.deleteVariableArgsForCall)
}

func (fake *FakeClientInterface) DeleteVariableCalls(stub func(string) error) {
	fake.deleteVariableMutex.Lock()
	defer fake.deleteVariableMutex.Unlock()
	fake.DeleteVariableStub = stub
}

func (fake *FakeClientInterface) DeleteVariableArgsForCall(i int) string {
	fake.deleteVariableMutex.RLock()
	defer fake.deleteVariableMutex.RUnlock()
	argsForCall := fake.deleteVariableArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) DeleteVariableReturns(result1 error) {
	fake.deleteVariableMutex.Lock()
	defer fake.deleteVariableMutex.Unlock()
	fake.DeleteVariableStub = nil
	fake.deleteVariableReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientInterface) DeleteVariableReturnsOnCall(i int, result1 error) {
	fake.deleteVariableMutex.Lock()
	defer fake.deleteVariableMutex.Unlock()
	fake.DeleteVariableStub = nil
	if fake.deleteVariableReturnsOnCall == nil {
		fake.deleteVariableReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteVariableReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientInterface) GetCredentialSchema(arg1 string) (map[string]interface{}, error) {
	fake.getCredentialSchemaMutex.Lock()
	ret, specificReturn := fake.getCredentialSchemaReturnsOnCall[len(fake.getCredentialSchemaArgsForCall)]
	fake.getCredentialSchemaArgsForCall = append(fake.getCredentialSchemaArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetCredentialSchemaStub
	fakeReturns := fake.getCredentialSchemaReturns
	fake.recordInvocation("GetCredentialSchema", []interface{}{arg1})
	fake.getCredentialSchemaMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) GetCredentialSchemaCallCount() int {
	fake.getCredentialSchemaMutex.RLock()
	defer fake.getCredentialSchemaMutex.RUnlock()
	return len(fake.getCredentialSchemaArgsForCall)
}

func (fake *FakeClientInterface) GetCredentialSchemaCalls(stub func(string) (map[string]interface{}, error)) {
	fake.getCredentialSchemaMutex.Lock()
	defer fake.getCredentialSchemaMutex.Unlock()
	fake.GetCredentialSchemaStub = stub
}

func (fake *FakeClientInterface) GetCredentialSchemaArgsForCall(i int) string {
	fake.getCredentialSchemaMutex.RLock()
	defer fake.getCredentialSchemaMutex.RUnlock()
	argsForCall := fake.getCredentialSchemaArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) GetCredentialSchemaReturns(result1 map[string]interface{}, result2 error) {
	fake.getCredentialSchemaMutex.Lock()
	defer fake.getCredentialSchemaMutex.Unlock()
	fake.GetCredentialSchemaStub = nil
	fake.getCredentialSchemaReturns = struct {
		result1 map[string]interface{}
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GetCredentialSchemaReturnsOnCall(i int, result1 map[string]interface{}, result2 error) {
	fake.getCredentialSchemaMutex.Lock()
	defer fake.getCredentialSchemaMutex.Unlock()
	fake.GetCredentialSchemaStub = nil
	if fake.getCredentialSchemaReturnsOnCall == nil {
		fake.getCredentialSchemaReturnsOnCall = make(map[int]struct {
			result1 map[string]interface{}
			result2 error
		})
	}
	fake.getCredentialSchemaReturnsOnCall[i] = struct {
		result1 map[string]interface{}
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GetProjects(arg1 *int, arg2 string) (*n8n.ProjectList, error) {
	fake.getProjectsMutex.Lock()
	ret, specificReturn := fake.getProjectsReturnsOnCall[len(fake.getProjectsArgsForCall)]
	fake.getProjectsArgsForCall = append(fake.getProjectsArgsForCall, struct {
		arg1 *int
		arg2 string
	}{arg1, arg2})
	stub := fake.GetProjectsStub
	fakeReturns := fake.getProjectsReturns
	fake.recordInvocation("GetProjects", []interface{}{arg1, arg2})
	fake.getProjectsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) GetProjectsCallCount() int {
	fake.getProjectsMutex.RLock()
	defer fake.getProjectsMutex.RUnlock()
	return len(fake.getProjectsArgsForCall)
}

func (fake *FakeClientInterface) GetProjectsCalls(stub func(*int, string) (*n8n.ProjectList, error)) {
	fake.getProjectsMutex.Lock()
	defer fake.getProjectsMutex.Unlock()
	fake.GetProjectsStub = stub
}

func (fake *FakeClientInterface) GetProjectsArgsForCall(i int) (*int, string) {
	fake.getProjectsMutex.RLock()
	defer fake.getProjectsMutex.RUnlock()
	argsForCall := fake.getProjectsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClientInterface) GetProjectsReturns(result1 *n8n.ProjectList, result2 error) {
	fake.getProjectsMutex.Lock()
	defer fake.getProjectsMutex.Unlock()
	fake.GetProjectsStub = nil
	fake.getProjectsReturns = struct {
		result1 *n8n.ProjectList
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GetProjectsReturnsOnCall(i int, result1 *n8n.ProjectList, result2 error) {
	fake.getProjectsMutex.Lock()
	defer fake.getProjectsMutex.Unlock()
	fake.GetProjectsStub = nil
	if fake.getProjectsReturnsOnCall == nil {
		fake.getProjectsReturnsOnCall = make(map[int]struct {
			result1 *n8n.ProjectList
			result2 error
		})
	}
	fake.getProjectsReturnsOnCall[i] = struct {
		result1 *n8n.ProjectList
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GetVariables(arg1 *int, arg2 string) (*n8n.VariableList, error) {
	fake.getVariablesMutex.Lock()
	ret, specificReturn := fake.getVariablesReturnsOnCall[len(fake.getVariablesArgsForCall)]
	fake.getVariablesArgsForCall = append(fake.getVariablesArgsForCall, struct {
		arg1 *int
		arg2 string
	}{arg1, arg2})
	stub := fake.GetVariablesStub
	fakeReturns := fake.getVariablesReturns
	fake.recordInvocation("GetVariables", []interface{}{arg1, arg2})
	fake.getVariablesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) GetVariablesCallCount() int {
	fake.getVariablesMutex.RLock()
	defer fake.getVariablesMutex.RUnlock()
	return len(fake.getVariablesArgsForCall)
}

func (fake *FakeClientInterface) GetVariablesCalls(stub func(*int, string) (*n8n.VariableList, error)) {
	fake.getVariablesMutex.Lock()
	defer fake.getVariablesMutex.Unlock()
	fake.GetVariablesStub = stub
}

func (fake *FakeClientInterface) GetVariablesArgsForCall(i int) (*int, string) {
	fake.getVariablesMutex.RLock()
	defer fake.getVariablesMutex.RUnlock()
	argsForCall := fake.getVariablesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClientInterface) GetVariablesReturns(result1 *n8n.VariableList, result2 error) {
	fake.getVariablesMutex.Lock()
	defer fake.getVariablesMutex.Unlock()
	fake.GetVariablesStub = nil
	fake.getVariablesReturns = struct {
		result1 *n8n.VariableList
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GetVariablesReturnsOnCall(i int, result1 *n8n.VariableList, result2 error) {
	fake.getVariablesMutex.Lock()
	defer fake.getVariablesMutex.Unlock()
	fake.GetVariablesStub = nil
	if fake.getVariablesReturnsOnCall == nil {
		fake.getVariablesReturnsOnCall = make(map[int]struct {
			result1 *n8n.VariableList
			result2 error
		})
	}
	fake.getVariablesReturnsOnCall[i] = struct {
		result1 *n8n.VariableList
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) RetryExecution(arg1 string, arg2 bool) (*n8n.Execution, error) {
	fake.retryExecutionMutex.Lock()
	ret, specificReturn := fake.retryExecutionReturnsOnCall[len(fake.retryExecutionArgsForCall)]
	fake.retryExecutionArgsForCall = append(fake.retryExecutionArgsForCall, struct {
		arg1 string
		arg2 bool
	}{arg1, arg2})
	stub := fake.RetryExecutionStub
	fakeReturns := fake.retryExecutionReturns
	fake.recordInvocation("RetryExecution", []interface{}{arg1, arg2})
	fake.retryExecutionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) RetryExecutionCallCount() int {
	fake.retryExecutionMutex.RLock()
	defer fake.retryExecutionMutex.RUnlock()
	return len(fake.retryExecutionArgsForCall)
}

func (fake *FakeClientInterface) RetryExecutionCalls(stub func(string, bool) (*n8n.Execution, error)) {
	fake.retryExecutionMutex.Lock()
	defer fake.retryExecutionMutex.Unlock()
	fake.RetryExecutionStub = stub
}

func (fake *FakeClientInterface) RetryExecutionArgsForCall(i int) (string, bool) {
	fake.retryExecutionMutex.RLock()
	defer fake.retryExecutionMutex.RUnlock()
	argsForCall := fake.retryExecutionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClientInterface) RetryExecutionReturns(result1 *n8n.Execution, result2 error) {
	fake.retryExecutionMutex.Lock()
	defer fake.retryExecutionMutex.Unlock()
	fake.RetryExecutionStub = nil
	fake.retryExecutionReturns = struct {
		result1 *n8n.Execution
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) RetryExecutionReturnsOnCall(i int, result1 *n8n.Execution, result2 error) {
	fake.retryExecutionMutex.Lock()
	defer fake.retryExecutionMutex.Unlock()
	fake.RetryExecutionStub = nil
	if fake.retryExecutionReturnsOnCall == nil {
		fake.retryExecutionReturnsOnCall = make(map[int]struct {
			result1 *n8n.Execution
			result2 error
		})
	}
	fake.retryExecutionReturnsOnCall[i] = struct {
		result1 *n8n.Execution
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) UpdateVariable(arg1 string, arg2 *n8n.Variable) error {
	fake.updateVariableMutex.Lock()
	ret, specificReturn := fake.updateVariableReturnsOnCall[len(fake.updateVariableArgsForCall)]
	fake.updateVariableArgsForCall = append(fake.updateVariableArgsForCall, struct {
		arg1 string
		arg2 *n8n.Variable
	}{arg1, arg2})
	stub := fake.UpdateVariableStub
	fakeReturns := fake.updateVariableReturns
	fake.recordInvocation("UpdateVariable", []interface{}{arg1, arg2})
	fake.updateVariableMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClientInterface) UpdateVariableCallCount() int {
	fake.updateVariableMutex.RLock()
	defer fake.updateVariableMutex.RUnlock()
	return len(fake.updateVariableArgsForCall)
}

func (fake *FakeClientInterface) UpdateVariableCalls(stub func(string, *n8n.Variable) error) {
	fake.updateVariableMutex.Lock()
	defer fake.updateVariableMutex.Unlock()
	fake.UpdateVariableStub = stub
}

func (fake *FakeClientInterface) UpdateVariableArgsForCall(i int) (string, *n8n.Variable) {
	fake.updateVariableMutex.RLock()
	defer fake.updateVariableMutex.RUnlock()
	argsForCall := fake.updateVariableArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClientInterface) UpdateVariableReturns(result1 error) {
	fake.updateVariableMutex.Lock()
	defer fake.updateVariableMutex.Unlock()
	fake.UpdateVariableStub = nil
	fake.updateVariableReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientInterface) UpdateVariableReturnsOnCall(i int, result1 error) {
	fake.updateVariableMutex.Lock()
	defer fake.updateVariableMutex.Unlock()
	fake.UpdateVariableStub = nil
	if fake.updateVariableReturnsOnCall == nil {
		fake.updateVariableReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateVariableReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientInterface) UpdateWorkflow(arg1 string, arg2 *n8n.Workflow) (*n8n.Workflow, error) {
	fake.updateWorkflowMutex.Lock()
	ret, specificReturn := fake.updateWorkflowReturnsOnCall[len(fake.updateWorkflowArgsForCall)]
	fake.updateWorkflowArgsForCall = append(fake.updateWorkflowArgsForCall, struct {
		arg1 string
		arg2 *n8n.Workflow
	}{arg1, arg2})
	stub := fake.UpdateWorkflowStub
	fakeReturns := fake.updateWorkflowReturns
	fake.recordInvocation("UpdateWorkflow", []interface{}{arg1, arg2})
	fake.updateWorkflowMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) UpdateWorkflowCallCount() int {
	fake.updateWorkflowMutex.RLock()
	defer fake.updateWorkflowMutex.RUnlock()
	return len(fake.updateWorkflowArgsForCall)
}

func (fake *FakeClientInterface) UpdateWorkflowCalls(stub func(string, *n8n.Workflow) (*n8n.Workflow, error)) {
	fake.updateWorkflowMutex.Lock()
	defer fake.updateWorkflowMutex.Unlock()
	fake.UpdateWorkflowStub = stub
}

func (fake *FakeClientInterface) UpdateWorkflowArgsForCall(i int) (string, *n8n.Workflow) {
	fake.updateWorkflowMutex.RLock()
	defer fake.updateWorkflowMutex.RUnlock()
	argsForCall := fake.updateWorkflowArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClientInterface) UpdateWorkflowReturns(result1 *n8n.Workflow, result2 error) {
	fake.updateWorkflowMutex.Lock()
	defer fake.updateWorkflowMutex.Unlock()
	fake.UpdateWorkflowStub = nil
	fake.updateWorkflowReturns = struct {
		result1 *n8n.Workflow
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) UpdateWorkflowReturnsOnCall(i int, result1 *n8n.Workflow, result2 error) {
	fake.updateWorkflowMutex.Lock()
	defer fake.updateWorkflowMutex.Unlock()
	fake.UpdateWorkflowStub = nil
	if fake.updateWorkflowReturnsOnCall == nil {
		fake.updateWorkflowReturnsOnCall = make(map[int]struct {
			result1 *n8n.Workflow
			result2 error
		})
	}
	fake.updateWorkflowReturnsOnCall[i] = struct {
		result1 *n8n.Workflow
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) UpdateWorkflowTags(arg1 string, arg2 n8n.TagIds) (n8n.WorkflowTags, error) {
	fake.updateWorkflowTagsMutex.Lock()
	ret, specificReturn := fake.updateWorkflowTagsReturnsOnCall[len(fake.updateWorkflowTagsArgsForCall)]
	fake.updateWorkflowTagsArgsForCall = append(fake.updateWorkflowTagsArgsForCall, struct {
		arg1 string
		arg2 n8n.TagIds
	}{arg1, arg2})
	stub := fake.UpdateWorkflowTagsStub
	fakeReturns := fake.updateWorkflowTagsReturns
	fake.recordInvocation("UpdateWorkflowTags", []interface{}{arg1, arg2})
	fake.updateWorkflowTagsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) UpdateWorkflowTagsCallCount() int {
	fake.updateWorkflowTagsMutex.RLock()
	defer fake.updateWorkflowTagsMutex.RUnlock()
	return len(fake.updateWorkflowTagsArgsForCall)
}

func (fake *FakeClientInterface) UpdateWorkflowTagsCalls(stub func(string, n8n.TagIds) (n8n.WorkflowTags, error)) {
	fake.updateWorkflowTagsMutex.Lock()
	defer fake.updateWorkflowTagsMutex.Unlock()
	fake.UpdateWorkflowTagsStub = stub
}

func (fake *FakeClientInterface) UpdateWorkflowTagsArgsForCall(i int) (string, n8n.TagIds) {
	fake.updateWorkflowTagsMutex.RLock()
	defer fake.updateWorkflowTagsMutex.RUnlock()
	argsForCall := fake.updateWorkflowTagsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClientInterface) UpdateWorkflowTagsReturns(result1 n8n.WorkflowTags, result2 error) {
	fake.updateWorkflowTagsMutex.Lock()
	defer fake.updateWorkflowTagsMutex.Unlock()
	fake.UpdateWorkflowTagsStub = nil
	fake.updateWorkflowTagsReturns = struct {
		result1 n8n.WorkflowTags
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) UpdateWorkflowTagsReturnsOnCall(i int, result1 n8n.WorkflowTags, result2 error) {
	fake.updateWorkflowTagsMutex.Lock()
	defer fake.updateWorkflowTagsMutex.Unlock()
	fake.UpdateWorkflowTagsStub = nil
	if fake.updateWorkflowTagsReturnsOnCall == nil {
		fake.updateWorkflowTagsReturnsOnCall = make(map[int]struct {
			result1 n8n.WorkflowTags
			result2 error
		})
	}
	fake.updateWorkflowTagsReturnsOnCall[i] = struct {
		result1 n8n.WorkflowTags
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GenerateAudit(arg1 *n8n.PostAuditJSONBody) (*n8n.Audit, error) {
	fake.generateAuditMutex.Lock()
	ret, specificReturn := fake.generateAuditReturnsOnCall[len(fake.generateAuditArgsForCall)]
	fake.generateAuditArgsForCall = append(fake.generateAuditArgsForCall, struct {
		arg1 *n8n.PostAuditJSONBody
	}{arg1})
	stub := fake.GenerateAuditStub
	fakeReturns := fake.generateAuditReturns
	fake.recordInvocation("GenerateAudit", []interface{}{arg1})
	fake.generateAuditMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientInterface) GenerateAuditCallCount() int {
	fake.generateAuditMutex.RLock()
	defer fake.generateAuditMutex.RUnlock()
	return len(fake.generateAuditArgsForCall)
}

func (fake *FakeClientInterface) GenerateAuditCalls(stub func(*n8n.PostAuditJSONBody) (*n8n.Audit, error)) {
	fake.generateAuditMutex.Lock()
	defer fake.generateAuditMutex.Unlock()
	fake.GenerateAuditStub = stub
}

func (fake *FakeClientInterface) GenerateAuditArgsForCall(i int) *n8n.PostAuditJSONBody {
	fake.generateAuditMutex.RLock()
	defer fake.generateAuditMutex.RUnlock()
	argsForCall := fake.generateAuditArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientInterface) GenerateAuditReturns(result1 *n8n.Audit, result2 error) {
	fake.generateAuditMutex.Lock()
	defer fake.generateAuditMutex.Unlock()
	fake.GenerateAuditStub = nil
	fake.generateAuditReturns = struct {
		result1 *n8n.Audit
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) GenerateAuditReturnsOnCall(i int, result1 *n8n.Audit, result2 error) {
	fake.generateAuditMutex.Lock()
	defer fake.generateAuditMutex.Unlock()
	fake.GenerateAuditStub = nil
	if fake.generateAuditReturnsOnCall == nil {
		fake.generateAuditReturnsOnCall = make(map[int]struct {
			result1 *n8n.Audit
			result2 error
		})
	}
	fake.generateAuditReturnsOnCall[i] = struct {
		result1 *n8n.Audit
		result2 error
	}{result1, result2}
}

func (fake *FakeClientInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.activateWorkflowMutex.RLock()
	defer fake.activateWorkflowMutex.RUnlock()
	fake.createCredentialMutex.RLock()
	defer fake.createCredentialMutex.RUnlock()
	fake.createProjectMutex.RLock()
	defer fake.createProjectMutex.RUnlock()
	fake.createTagMutex.RLock()
	defer fake.createTagMutex.RUnlock()
	fake.createVariableMutex.RLock()
	defer fake.createVariableMutex.RUnlock()
	fake.createWorkflowMutex.RLock()
	defer fake.createWorkflowMutex.RUnlock()
	fake.deactivateWorkflowMutex.RLock()
	defer fake.deactivateWorkflowMutex.RUnlock()
	fake.deleteCredentialMutex.RLock()
	defer fake.deleteCredentialMutex.RUnlock()
	fake.generateAuditMutex.RLock()
	defer fake.generateAuditMutex.RUnlock()
	fake.deleteExecutionMutex.RLock()
	defer fake.deleteExecutionMutex.RUnlock()
	fake.deleteVariableMutex.RLock()
	defer fake.deleteVariableMutex.RUnlock()
	fake.deleteWorkflowMutex.RLock()
	defer fake.deleteWorkflowMutex.RUnlock()
	fake.getCredentialSchemaMutex.RLock()
	defer fake.getCredentialSchemaMutex.RUnlock()
	fake.getExecutionByIdMutex.RLock()
	defer fake.getExecutionByIdMutex.RUnlock()
	fake.getExecutionsMutex.RLock()
	defer fake.getExecutionsMutex.RUnlock()
	fake.getProjectsMutex.RLock()
	defer fake.getProjectsMutex.RUnlock()
	fake.getTagsMutex.RLock()
	defer fake.getTagsMutex.RUnlock()
	fake.getVariablesMutex.RLock()
	defer fake.getVariablesMutex.RUnlock()
	fake.getWorkflowMutex.RLock()
	defer fake.getWorkflowMutex.RUnlock()
	fake.getWorkflowTagsMutex.RLock()
	defer fake.getWorkflowTagsMutex.RUnlock()
	fake.getWorkflowsMutex.RLock()
	defer fake.getWorkflowsMutex.RUnlock()
	fake.retryExecutionMutex.RLock()
	defer fake.retryExecutionMutex.RUnlock()
	fake.updateVariableMutex.RLock()
	defer fake.updateVariableMutex.RUnlock()
	fake.updateWorkflowMutex.RLock()
	defer fake.updateWorkflowMutex.RUnlock()
	fake.updateWorkflowTagsMutex.RLock()
	defer fake.updateWorkflowTagsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClientInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ n8n.ClientInterface = new(FakeClientInterface)
